name: Print Secret

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  print_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret Value
        run: echo "${{secrets.VAR}}"

      - name: Check Secret Value
        run: |
          if [ "${{ secrets.VAR }}" = "This is a secret" ]; then
            echo "The secret value matches the desired value."
          else
            echo "The secret value does not match the desired value."
          fi
        
