name: Print Secret

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Tag
        run: |
          git tag -a "v1.0" -m "Version v1.0"
          git push origin main --follow-tags

  print_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret Value
        run: echo "${{secrets.VAR}}"

      - name: Check Secret Value
        run: |
          if [ "${{ secrets.VAR }}" = "This is a secret" ]; then
            echo "The secret value matches the desired value."
          else
            echo "The secret value does not match the desired value."
          fi
        
