name: Print Secret

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret Value
        run: echo "${{secrets.VAR}}"
