name: Create Release and Tag

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Tag
        run: |
          git tag -a "v4.0" -m "Version v4.0"
          git push origin main --follow-tags

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: "v4.0"
          release_name: "Release v4.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
